/** Source-of-truth shop catalog for Discord-native VP. */
export const ECONOMY_CATALOG = [
  {
    id: "early-adopter",
    slot: "title",
    tier: "starter",
    name: "Early Adopter",
    description: "Here before the crowd.",
    cost: 0,
    tag: "LIMITED",
  },
  {
    id: "vortality",
    slot: "badge",
    tier: "starter",
    name: "Vortality",
    description: "Granted for being in the Discord server.",
    cost: 0,
    icon: "noob",
    tag: "COMMUNITY",
    grantOnly: true,
  },
  {
    id: "v07-unpacked",
    slot: "badge",
    tier: "common",
    name: "Unpacked",
    description: "Running Vortex07 from source.",
    cost: 50,
    icon: "noob",
  },
  {
    id: "guest-visitor",
    slot: "badge",
    tier: "common",
    name: "Guestbook Guest",
    description: "Leaves kind words on profiles.",
    cost: 60,
    icon: "noob",
  },
  {
    id: "night-owl",
    slot: "title",
    tier: "common",
    name: "Night Owl",
    description: "Dark mode loyalist.",
    cost: 80,
  },
  {
    id: "game-critic",
    slot: "badge",
    tier: "common",
    name: "Game Critic",
    description: "Rates games on playvortex.",
    cost: 90,
    icon: "noob",
  },
  {
    id: "forum-regular",
    slot: "title",
    tier: "common",
    name: "Forum Regular",
    description: "Active in Community.",
    cost: 60,
    requireRep: 5,
  },
  {
    id: "rep-ten",
    slot: "badge",
    tier: "rare",
    name: "Rep 10+",
    description: "Trusted on the leaderboard.",
    cost: 0,
    icon: "noob",
    requireRep: 10,
    tag: "REP",
    grantOnly: true,
  },
  {
    id: "beta-26",
    slot: "title",
    tier: "rare",
    name: "Beta '26",
    description: "Vortex07 beta season.",
    cost: 200,
  },
  {
    id: "frame-purple",
    slot: "frame",
    tier: "rare",
    name: "Purple Rim",
    description: "Classic Vortex07 border.",
    cost: 280,
    frameClass: "vortex07-economy-frame-purple",
  },
  {
    id: "frame-gold",
    slot: "frame",
    tier: "rare",
    name: "Gold Rim",
    description: "Earned from the grind.",
    cost: 400,
    frameClass: "vortex07-economy-frame-gold",
  },
  {
    id: "theme-midnight",
    slot: "frame",
    tier: "limited",
    name: "Midnight",
    description: "Deep purple profile theme.",
    cost: 500,
    tag: "THEME",
    frameClass: "vortex07-economy-frame-midnight",
  },
  {
    id: "theme-aurora",
    slot: "frame",
    tier: "limited",
    name: "Aurora",
    description: "Teal & violet rim glow.",
    cost: 750,
    tag: "THEME",
    frameClass: "vortex07-economy-frame-aurora",
  },
  {
    id: "theme-neon",
    slot: "frame",
    tier: "limited",
    name: "Neon Vortex",
    description: "Electric pink-purple neon.",
    cost: 900,
    tag: "THEME",
    frameClass: "vortex07-economy-frame-neon",
  },
  {
    id: "theme-legend",
    slot: "frame",
    tier: "limited",
    name: "Legend",
    description: "Gold crown frame — endgame flex.",
    cost: 1200,
    tag: "THEME",
    frameClass: "vortex07-economy-frame-legend",
  },
];

export const ECONOMY_TIER_ORDER = ["starter", "common", "rare", "limited"];

export function getCatalogItem(itemId) {
  return ECONOMY_CATALOG.find((i) => i.id === String(itemId || "").toLowerCase()) || null;
}
